theme: jekyll-theme-minimal
title: POC Dijkstra
description: A proof of compect of Dijkstra algorithm
logo: https://raw.githubusercontent.com/guibranco/POC-Dijkstra/master/logo.jpg
show_downloads: true